# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI
# Trigger the workflow on push or pull reuest events only for the main branch 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     #step1: Checkout the code from the repository 
    - name: Checkout code
      uses: actions/checkout@v2

      #step2: Setup the python Environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with: 
        python-version: '3.8'
      
      #step3: Install the dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
      
      #step4: Run the tests
    - name: Run Tests
      run: pytest 

   